### ISSUE TITLE
Open DIS logo image

### ISSUE THREAD

**Issue by brutzman** [open-dis/open-dis7-java#1]
We need to document the source of the OpenDIS surfer logo to confirm that we have rights to publish openly.

Thanks to the inestimable Don McGregor for first posing this image as our cool logo.

**Comment by sirtobi79** [comment]
Using the google image search leads to:
https://www.pinterest.com/pin/219620919311232008/ which leads http://www.imagui.com/a/logo-surf-ioebGR89r

There the image can be downloaded for free.

**Comment by brutzman** [comment]
Reportedly license free on this site.  Thanks Tobi.
